# Database config (Update if needed)
spring.datasource.url=jdbc:h2:mem:eventsdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# Jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway
spring.flyway.enabled=false

# Security
security.jwt.secret=secret
security.jwt.expiration=3600000

# Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=profile-vitaile
management.metrics.tags.env=dev

# Vertex Ai
spring.ai.vertex.ai.gemini.project-id={}
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.model=gemini-1.5-pro