# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:eventsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# =====================
# ACTUATOR
# =====================
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=when_authorized

# =====================
# PROMETHEUS
# =====================
management.metrics.export.prometheus.enabled=true

# =====================
# METRICS TAGS (IMPORTANTES)
# =====================
management.metrics.tags.application=profile-vitaile
management.metrics.tags.env=dev
# ===============================
# VERTEX AI - GEMINI
# ===============================
spring.ai.vertex.ai.gemini.project-id={}
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.model=gemini-1.5-pro


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.flyway.enabled=true