package showtime_corp.profile_vitaile.entity.resumen;

import java.util.List;

/**
 * Represents the detailed AI-generated resume information.
 * <p>
 * This object is stored as JSON in the column {@code resume_info}.
 * It contains structured professional data extracted or generated by AI.
 * </p>
 */
public class ResumeInfo {

    /**
     * Professional title or headline.
     */
    private String title;

    /**
     * Professional summary describing the user's profile.
     */
    private String summary;

    /**
     * List of technical and soft skills.
     */
    private List<String> skills;

    /**
     * Work experience entries.
     */
    private List<String> experience;

    /**
     * Educational background.
     */
    private List<String> education;


}
